### ISSUE TITLE
Add project: Rezo de los Mil Jesús

### ISSUE THREAD

**Issue by emamut** [servusdei2018/awesome-catholic#28]
**Project name:** Rezo de los Mil Jesús
**Project url:** [https://rezo-mil-jesus.netlify.app](https://rezo-mil-jesus.netlify.app/)
**Project description:** Connect your faith with the ancestral tradition. Our digital platform invites you to immerse yourself in the devotion of Los Mil Jesús, a spiritual practice that unites believers in the invocation of the name of Jesus for the protection and blessing of the home.

**Comment by GomezMig03** [comment]
Looks like a good idea, nice job!

**Comment by servusdei2018** [comment]
Great project, added it to the list. I will have to start this devotion myself, thank you!

**Comment by emamut** [comment]
Thank you very much for your support! I hope this Latin American devotion will be useful. I also thank you for this beautiful project
