### ISSUE TITLE
Add project(s)

### ISSUE THREAD

**Issue by kas-catholic** [servusDei2018/awesome-catholic#4]
**Project name:** [ConfessIt](https://confessit.app)
**Project url:** https://github.com/kas-catholic/confessit-web
**Project description:** A progressive web app designed to help Roman Catholics prepare for the sacrament of confession by examining their conscience.

I maintain ConfessIt, and I'd be happy to open the PR if you'd like to include this in your list!

**Comment by servusDei2018** [comment]
Sure, that looks like an awesome project, thank you! 😸 For the translations of the list I use Google translate, but any others would work just as well.
