### ISSUE TITLE
Open-source only?

### ISSUE THREAD

**Issue by 2br-2b** [servusDei2018/awesome-catholic#5]
Hello! Thank you so much for making this list!

It seems that this list only includes open source Catholic resources. Is that correct? If not, I can add a few, but if so, it may be helpful to clarify this on the list.

Thank you!

**Comment by servusDei2018** [comment]
@2br-2b  You're welcome, thank you for your interest!! 😺 

The main focus of the list is to showcase open source Catholic projects, since they deserve more attention, but if a commercial product has an API or something like that which is publicly accessible, it would fit in.
