### ISSUE TITLE
Add project(s) - Ember Days, St. Andrew Novena, LiturgicalCalendar

### ISSUE THREAD

**Issue by mftruso** [servusDei2018/awesome-catholic#7]
**Project name:** Ember Days
**Project url:** https://github.com/saint-isidore-guild/ember-days
**Project description:** Display the Ember Days for a given year

**Project name:** St. Andrew Novena Mobile App
**Project url:** https://github.com/mftruso/st-andrew-novena
**Project description:** Flutter app to count daily recitations of the St. Andrew novena prayer, 15 times daily. 

**Project name:** LiturgicalCalendar
**Project url:** https://github.com/JohnRDOrazio/LiturgicalCalendar
**Project description:** A PHP script that will generate the liturgical calendar for any given year, based on the General Roman Calendar, calculating the mobile festivities and the precedence of solemnities, feasts, memorials

**Comment by servusDei2018** [comment]
Awesome, thank you! The mobile app especially is beautiful.
